[[OpenLDAPClient]]
arch = "aarch64"
git-tree-sha1 = "98404b57bd38a1a8593073ac8e7aecdd9dd52eab"
os = "macos"

    [[OpenLDAPClient.download]]
    sha256 = "eea20977490a2cc823c8ce80d11c83246c91932ce85b8e729690a0dc55260652"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.aarch64-apple-darwin.tar.gz"
[[OpenLDAPClient]]
arch = "aarch64"
git-tree-sha1 = "a8e344868172008c7f25d04272a878bc1ac26167"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "6bd7e7c589d7f1eb15941a7f16f08994a7b0de9306749eb00c9623b05fa269cf"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.aarch64-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "aarch64"
git-tree-sha1 = "e3853bbcf97d7fc8707da12cc2d7b7f7487c31ee"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "41135179590fffc5ff749cc03d0eb6945f6e4cc49dc4c4ed6edb466541e3fcd3"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.aarch64-linux-musl.tar.gz"
[[OpenLDAPClient]]
arch = "aarch64"
git-tree-sha1 = "6c8ec894fa70f963741043c8d816172c0ce01aed"
os = "freebsd"

    [[OpenLDAPClient.download]]
    sha256 = "d01f94de0e3a3f7cb5256c475eafffe75f6056125b743a5d1d5e1c1b00d3cadb"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.aarch64-unknown-freebsd.tar.gz"
[[OpenLDAPClient]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55f81961b4e22d2f115559eef15615247aadb67a"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "18ba87fead7854937432fb9a052420dab0186f547ce90093bf8546a3ae45b291"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.armv6l-linux-gnueabihf.tar.gz"
[[OpenLDAPClient]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6397a6f7229030fed1a493e325c57eb3253ba67b"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "6b55833203e4faac8044ac470ba4a1b166a9d4fed6f8ca1e356c16d045fc8191"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.armv6l-linux-musleabihf.tar.gz"
[[OpenLDAPClient]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be85a5f5e25158d8a1a28631324435314c306be9"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "43ccb95b08eeb0866906749e987c6c976ac261136a828bc8d9f86352be55c668"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.armv7l-linux-gnueabihf.tar.gz"
[[OpenLDAPClient]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5139c3b0e368766bfc9e741f01953e41f9036a22"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "2c09e724e5bbc1af084e9b735a5838a9141701f05d4d6e1391257e9d2a44d42c"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.armv7l-linux-musleabihf.tar.gz"
[[OpenLDAPClient]]
arch = "i686"
git-tree-sha1 = "b61b6762a9d7a9ca7fb044026495cfe61efc7513"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "67b1e64947d5b54688cd2fb2f5fea0f2e7995f818dc2744c4965c8ac79b94ab2"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.i686-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "i686"
git-tree-sha1 = "69d32d9addb07cc1ceb1dcd2383fd1718e5f416d"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "5e3497cf21ed57af95083a58717ead5c5fc8fad9ec291bdb7a08198d903e9e8c"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.i686-linux-musl.tar.gz"
[[OpenLDAPClient]]
arch = "i686"
git-tree-sha1 = "218fab1505c9e6fac95b6b72510bac184b8755ad"
os = "windows"

    [[OpenLDAPClient.download]]
    sha256 = "e370f9abcc3bb888a9a24d206c6048e815a380869736c93753d64e324d679541"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.i686-w64-mingw32.tar.gz"
[[OpenLDAPClient]]
arch = "powerpc64le"
git-tree-sha1 = "c6d9e111a43f3dd668bb6956092d00d59bfba7e7"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "f00b123d5e9408e5bc01cc42ea50699131ba18c976035a8241add178b2cebcd7"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.powerpc64le-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "riscv64"
git-tree-sha1 = "82ed6ea6cc4e400a04a1f72013709f558f0aa495"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "4b6aa8da27a78f3cf9f128688e94c8a6b1e273b7c2457ed51085088934e0423c"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.riscv64-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "9d8acadfe4b9a4b1d1ee7a2f84648adca69eb405"
os = "macos"

    [[OpenLDAPClient.download]]
    sha256 = "225902c612db468e81595849157a72f5450e0cc2d2604c22642c888eb5a97483"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.x86_64-apple-darwin.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "0232dcfd6c2122e61fa8190129b41dabbfa011c7"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "63c16d6bfd8219889b82b7e737ea1a660dc08091ed71faff9e20b4ef52be9246"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.x86_64-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "60c9822ab18794dcf88a3c411da7a42f6349e617"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "d897821d9e866b4515fccb9120ca684374581313aab3486aa4bfcfea2e73a26d"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.x86_64-linux-musl.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "cb4c16a39bf2482a481c032d8f09a4446a597aef"
os = "freebsd"

    [[OpenLDAPClient.download]]
    sha256 = "67693c237c7f4fda2ed3264bb5df59baa61cafcc9149c9275b96ddc11368b8d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.x86_64-unknown-freebsd.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "9a34da2c455187f99d561fa1e08b54f45c1abb2d"
os = "windows"

    [[OpenLDAPClient.download]]
    sha256 = "9b4c7ea12b4d36c57d711989585fde417111f3f033f716cdee0a33fb4d37d92b"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.19+0/OpenLDAPClient.v2.5.19.x86_64-w64-mingw32.tar.gz"
