[[OpenLDAPClient]]
arch = "aarch64"
git-tree-sha1 = "929ed503706c57b051e0a1a69c1d3ef2f29045f3"
os = "macos"

    [[OpenLDAPClient.download]]
    sha256 = "2b922b51b96e921d236d4a3e5fd249c1a1b432c3c3c9903c23ee72522f366709"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.aarch64-apple-darwin.tar.gz"
[[OpenLDAPClient]]
arch = "aarch64"
git-tree-sha1 = "7d89368c3569fcc2762616f402652bcde6b4d9e3"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "d23d59428c2af92535a8fe70b2890615085f772d6ed39a3963066c29586c73a5"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.aarch64-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "aarch64"
git-tree-sha1 = "74dafd50b27543e885a775aefae3823f4465309c"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "5c9cf5cb753953fa13ba279d5469c2e31875ce0f3b6ee5fa6db1aad4b2c906e9"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.aarch64-linux-musl.tar.gz"
[[OpenLDAPClient]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "744110c82a0213709c79d684f1216d03c6d0d147"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "223f1309ea829d3bec4e74eeb5a3177318ff15848a21bbbc24f07d98c261b800"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.armv6l-linux-gnueabihf.tar.gz"
[[OpenLDAPClient]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b842c2e98f503a5cdfbac68d20b185f1e696b58"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "347c260ba9c77d46f75f8eabdce19a5e89ccebce8b1439ebac8084784b4354d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.armv6l-linux-musleabihf.tar.gz"
[[OpenLDAPClient]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "732ca32bb64640331ab119b94ef6ace273d07eb7"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "c8b054b50aef7bc1d9339c02b451254203a67d990472b00224d6f29701d1d471"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.armv7l-linux-gnueabihf.tar.gz"
[[OpenLDAPClient]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "300fad9f8bdffbfc191a42ed6f940d604ec6ea81"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "f02fe30a31dfde99a07d894191cd2e2e671228505c03efd98b6824c01a2b2c3f"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.armv7l-linux-musleabihf.tar.gz"
[[OpenLDAPClient]]
arch = "i686"
git-tree-sha1 = "6bfe697302f9f7082c1bb074bb944fb57b43d8af"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "9a14db6bc8d23228ee7aa4c40225b6a56d5aa811678dca96f709018eaf026781"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.i686-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "i686"
git-tree-sha1 = "8d941eb3c469208b03459882a58702902a368699"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "98fa348d55a77c7424164a72a86dbfc956fe1cc016fb3d027bbbb6448d2b2cdf"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.i686-linux-musl.tar.gz"
[[OpenLDAPClient]]
arch = "i686"
git-tree-sha1 = "c5fc89958937deb4caa1e6a2cfa55cdc44e49a2b"
os = "windows"

    [[OpenLDAPClient.download]]
    sha256 = "b63d7ddf706a37e21a62107d586f2a66213cefefbcc67a3fa2677044d1702164"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.i686-w64-mingw32.tar.gz"
[[OpenLDAPClient]]
arch = "powerpc64le"
git-tree-sha1 = "aa55ab9802aac56ccc178fb08ff73fcbc23dafa4"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "cfeaab49d41aff8a8c1c3be2062ada1c451005fb3941056171ea34ae1ee03760"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.powerpc64le-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "f979f8a52d6706119eec1c9c9a3fbe7a764dd944"
os = "macos"

    [[OpenLDAPClient.download]]
    sha256 = "f184a7de70f792f21486868ceef8518543170e3cf390648e35d21a0628e36a1c"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.x86_64-apple-darwin.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "a8f4a395dc830882a522137d501afb07a1baa229"
libc = "glibc"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "188af39767ab232a3794f19cf8a52fa1323da0c5197a3447b0ffbee139d8456f"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.x86_64-linux-gnu.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "fe06ae319b890e292e8f224042e9119a40279739"
libc = "musl"
os = "linux"

    [[OpenLDAPClient.download]]
    sha256 = "8639a0a90e41cba8e5b66603051962e380352d7695cf1f8f5652743e7bc729ee"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.x86_64-linux-musl.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "0ef11ccbab3263a175c3c7d0ce994913da9de70c"
os = "freebsd"

    [[OpenLDAPClient.download]]
    sha256 = "5ee659bdf6046737f8222e43e7b04ac60d5300a86fc45ba6255a841336591056"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.x86_64-unknown-freebsd.tar.gz"
[[OpenLDAPClient]]
arch = "x86_64"
git-tree-sha1 = "7d56ec4550ab210ed403ec88944a021013425267"
os = "windows"

    [[OpenLDAPClient.download]]
    sha256 = "5dcfa5040ef3ebc89b93872718486a6a9f381654b1c129f38ec31b5fbdad91fd"
    url = "https://github.com/JuliaBinaryWrappers/OpenLDAPClient_jll.jl/releases/download/OpenLDAPClient-v2.5.14+0/OpenLDAPClient.v2.5.14.x86_64-w64-mingw32.tar.gz"
