# Autogenerated wrapper script for OpenLDAPClient_jll for x86_64-w64-mingw32
export ldapcompare, ldapdelete, ldapexop, ldapmodify, ldapmodrdn, ldappasswd, ldapsearch, ldapurl, ldapwhoami, liblber, libldap

using OpenSSL_jll
using PCRE_jll
JLLWrappers.@generate_wrapper_header("OpenLDAPClient")
JLLWrappers.@declare_library_product(liblber, "liblber.dll")
JLLWrappers.@declare_library_product(libldap, "libldap.dll")
JLLWrappers.@declare_executable_product(ldapcompare)
JLLWrappers.@declare_executable_product(ldapdelete)
JLLWrappers.@declare_executable_product(ldapexop)
JLLWrappers.@declare_executable_product(ldapmodify)
JLLWrappers.@declare_executable_product(ldapmodrdn)
JLLWrappers.@declare_executable_product(ldappasswd)
JLLWrappers.@declare_executable_product(ldapsearch)
JLLWrappers.@declare_executable_product(ldapurl)
JLLWrappers.@declare_executable_product(ldapwhoami)
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll, PCRE_jll)
    JLLWrappers.@init_library_product(
        liblber,
        "bin\\liblber.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libldap,
        "bin\\libldap.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ldapcompare,
        "bin\\ldapcompare.exe",
    )

    JLLWrappers.@init_executable_product(
        ldapdelete,
        "bin\\ldapdelete.exe",
    )

    JLLWrappers.@init_executable_product(
        ldapexop,
        "bin\\ldapexop.exe",
    )

    JLLWrappers.@init_executable_product(
        ldapmodify,
        "bin\\ldapmodify.exe",
    )

    JLLWrappers.@init_executable_product(
        ldapmodrdn,
        "bin\\ldapmodrdn.exe",
    )

    JLLWrappers.@init_executable_product(
        ldappasswd,
        "bin\\ldappasswd.exe",
    )

    JLLWrappers.@init_executable_product(
        ldapsearch,
        "bin\\ldapsearch.exe",
    )

    JLLWrappers.@init_executable_product(
        ldapurl,
        "bin\\ldapurl.exe",
    )

    JLLWrappers.@init_executable_product(
        ldapwhoami,
        "bin\\ldapwhoami.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
